services:
  - type: web
    name: blackthorn-nlp
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --listen=0.0.0.0:$PORT nlp_service:app
    autoDeploy: true