name: blackthorn_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flask
  - requests
  - numpy
  - scipy
  - scikit-learn
  - spacy
  - tensorflow
  - pytorch
  - pip
  - pip:
      - sentence-transformers
      - flask
      - flask-cors
      - gunicorn
      - sentence-transformers
      - torch
      - python-dotenv
